language: node_js
node_js:
  - '8'
  - '10'
  - '12'
notifications:
  email: false
jobs:
  include:
    - stage: npm release
      node_js: '10'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: 'mohit@mohitsingh.in'
        api_key: $NPM_API_KEY
        on:
          tags: true
          repo: mohitsinghs/eslint-config
